defmodule Visualize.Hooks do
  @moduledoc """
  Phoenix LiveView JavaScript hooks for interactive visualizations.

  This module provides hooks for:
  - Zoom and pan interactions
  - Brush selection

  ## Installation

  1. Generate the JavaScript file:

      mix visualize.gen.hooks

  Or manually create the file with:

      File.write!("assets/js/visualize_hooks.js", Visualize.Hooks.js_code())

  2. Import in your app.js:

      import { ZoomHook, BrushHook } from "./visualize_hooks"

      let liveSocket = new LiveSocket("/live", Socket, {
        hooks: { ZoomHook, BrushHook }
      })

  ## Usage Examples

  ### Zoom/Pan

      <svg phx-hook="ZoomHook" id="zoomable-chart" data-min-zoom="0.5" data-max-zoom="5">
        <g class="zoom-container">
          <!-- Chart content -->
        </g>
      </svg>

      # Handle zoom events
      def handle_event("zoom", %{"k" => scale, "x" => x, "y" => y}, socket) do
        {:noreply, assign(socket, transform: %{k: scale, x: x, y: y})}
      end

  ### Brush Selection

      <svg phx-hook="BrushHook" id="brush-chart" data-brush-type="x">
        <g class="chart-content">
          <!-- Chart content -->
        </g>
      </svg>

      # Handle brush events
      def handle_event("brush_select", %{"x0" => x0, "x1" => x1} = params, socket) do
        # Filter data or zoom to selection
        {:noreply, socket}
      end

  """

  alias Visualize.Hooks.{Zoom, Brush}

  @doc """
  Returns the complete JavaScript code for all hooks.

  Write this to a file in your assets directory.
  """
  def js_code do
    """
    // Visualize Hooks for Phoenix LiveView
    // Generated by Visualize.Hooks.js_code()

    #{Zoom.js_hook()}

    #{Brush.js_hook()}

    // Export all hooks
    export { ZoomHook, BrushHook };

    // Default export for convenience
    export default { ZoomHook, BrushHook };
    """
  end

  @doc """
  Returns the path where hooks should be installed.
  """
  def default_path do
    "assets/js/visualize_hooks.js"
  end

  @doc """
  Writes the hooks JavaScript to the default location.
  """
  def install! do
    path = default_path()
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, js_code())
    {:ok, path}
  end

  # Re-export helper functions from individual hook modules

  defdelegate transform_point(point, transform), to: Zoom
  defdelegate inverse_transform_point(point, transform), to: Zoom
  defdelegate identity_transform(), to: Zoom
  defdelegate scale_transform(transform, scale, center), to: Zoom
  defdelegate translate_transform(transform, dx, dy), to: Zoom

  defdelegate filter_selection(data, selection, opts), to: Brush
  defdelegate selection_to_domain(selection, opts), to: Brush
end
